### ISSUE TITLE
List of models to add for benchmarking

### ISSUE THREAD

**Issue by itsdfish** [StatisticalRethinkingJulia/MCMCBenchmarks.jl#1]
Hi Rob-

I would like to create a list of models to add to the benchmark set. In selecting the models, I think two criteria are worth considering: (1) convenience and (2) a range computational difficulty.  In terms of convenience, there are many models already developed, at least for some sampers.  Using a few models from statistical thinking is a sensible strategy since you already created models for various samplers. So this would largely be a matter of copy and pasting code to follow the templet I laid out in` Gaussian Example.jl` and standardizing the parameter names. 

In terms of computational difficulty, it might be good to identify simple models that are fairly easy from a computational standpoint and some others that are more challenging. With this approach, we would be able to see if and where some samplers become non-performant in some regard. I think hierarchical models are a good candidate for a difficult computational problem. One obvious benefit is that difficulty can be manipulated by changing that the number of lower level units (e.g subjects). I would also like to test a few cognitive models because they can be challenging in terms of correlated parameters and irregular likelihood surfaces. Here is a working list of models. Please feel free to add.

| Model    	| Author 	| Turing  	| DynamicHMC                      	| DynamicNUTS            	| CmdStan 	|
|----------	|--------	|---------	|---------------------------------	|------------------------	|---------	|
| LBA      	| Chris  	| Working 	| non-finite  density start point 	| Working                	| Working 	|
| SDT      	| Chris  	| Working 	| Coded, but errors               	| hard crash due  to NaN 	| Working 	|
| Gaussian 	| Chris  	| Working 	| Working                         	| Working                	| Working 	|
| Lin Reg. 	| Rob    	|         	|                                 	|                        	|         	|
| m12.6    	| Rob    	|         	|                                 	|                        	|         	|

**Comment by goedman** [comment]
Great list. Let's start with this list and possibly a few cognitive models. Shall I have a go at m12.6 to get familiar with the templates?

The master branch on my system seems to be working. I'll slowly refactor the source files a bit but that should be invisible from the Examples and Models I think. If master also works on your system we can delete your dev branch. For each example we can create a separate branch.

**Comment by itsdfish** [comment]
Sounds good. I'll start with signal detection, linear ballistic accumulator, and lognormal race, which are cognitive models. Go ahead and try m12.6 as you proposed. 

The master is working on my end although I haven't let the simulation complete. I can let you know when it finishes. 

Sure. I can create the examples on different branches. Do you want to keep them on different branches or just for development?

**Comment by itsdfish** [comment]
By the way, if you are looking for a smaller set of benchmarks, I'll suggest the following reduced list:

- [ ] Linear regression with variable number of coefficients
- [ ] Linear Ballistic Accumulator Model (Chris)
- [ ] m12.6 from Statistical Rethinking (Rob)

I think this would cover the most informative cases and would be manageable.

**Comment by goedman** [comment]
Why don’t you pick an additional cognitive model and I focus on the linear regression and multilevel model (12.6)? For now, let’s indeed keep it manageable!

**Comment by itsdfish** [comment]
Sounds like a plan. By the way, everything worked for me on master. Feel free to delete the chris_dev branch.

**Comment by itsdfish** [comment]
Hi Rob-

I added a table to keep track of progress and issues with regard to the benchmark models. Let me know if there is a better place for this information.

**Comment by goedman** [comment]
That is very useful. Maybe we should include it in the README for now?

**Comment by itsdfish** [comment]
Great idea. I added it to the README along with a more detailed description of the project.

**Comment by itsdfish** [comment]
I'll go ahead and close this since we seem to have settled on a set of models.
