### ISSUE TITLE
Bug: CmdStan model fails if a matrix of parameters is used

### ISSUE THREAD

**Issue by mkshirazi** [StatisticalRethinkingJulia/MCMCBenchmarks.jl#102]
```
ERROR: ArgumentError: index String[] not found
Stacktrace:
 [1] axisindexes(::Type{AxisArrays.Categorical}, ::Array{String,1}, ::Array{String,1}) at /home/mohibullahshirazi/.julia/packages/AxisArrays/IFpjG/src/indexing.jl:329
```

**Comment by mkshirazi** [comment]
I was working on a project when I realised that we run into this error whenever Cmdstan has a model parameter with more than one dimension.

**Comment by itsdfish** [comment]
Hi @mkshirazi. Would you be able to provide a MWE that creates this errror? That would help me look into possible solutions.

**Comment by mkshirazi** [comment]
I have created a pull request to address this change. 
https://github.com/StatisticalRethinkingJulia/MCMCBenchmarks.jl/pull/103

I dont understand what you mean by MWE

**Comment by itsdfish** [comment]
Thanks for the PR. I didn't see it initially. So I was asking for a simple example (often called a MWE) to investigate the error.

I will take a look at it later and merge it into master. Thanks again!

**Comment by mkshirazi** [comment]
Its late right now where I am from. I will write up an example tomorrow and put it out here.

**Comment by itsdfish** [comment]
No worries. A MWE is not necessary since you have found a solution.
