### ISSUE TITLE
Switch to GitHub actions

### ISSUE THREAD

**Issue by goedman** [StatisticalRethinkingJulia/MCMCBenchmarks.jl#117]
Hi Chris,

Hope you're doing ok and enjoy the holidays (sorting DataFrames???).

I've been thinking what options we have to switch MCMCBenchmarks.jl to Github (CI) actions as from Jan 1st 2021 I expect the allocated free Travis points will rapidly be depleted.

One problem I have with Stan's cmdstan is that I don't know how to install cmdstan in the GitHub CI environment (I'm going to ask on Stan discourse mailing list). 

Best,
Rob

**Comment by itsdfish** [comment]
Hi Rob-

I am doing well. I hope you are too. Thanks for bringing this to my attention. I am pasting a link to some information below. Let me know if there is any other pertinent information I should know about. I will look into this within the next few days. 

https://discourse.julialang.org/t/ann-required-updates-to-tagbot-yml/49249/7

**Comment by goedman** [comment]
You could probably copy the workflows (CI, ...) from the StatisticalRethinking.jl repo (or any other updated repo) and rename (or delete) the .travis.yml file. I think that should do it.

**Comment by itsdfish** [comment]
Thanks, Rob. I updated the repo. When I get time, I will need to update the code. I have to admit, I became fatigued from updating the package each time dependencies changed. Maintenance should be easier now that the ecosystem is starting to stabilize.
