### ISSUE TITLE
Sketch of Regression example

### ISSUE THREAD

**Issue by itsdfish** [StatisticalRethinkingJulia/MCMCBenchmarks.jl#12]
Hi Rob-

You noted in a previous comment that you were having trouble figuring out the framework. I sketched out the benchmark configuration on the branch CF_regression. In LinearRegression_example.jl, the number of data points and the number of coefficients are varied independently (of course, we could vary only one variable or something else entirely):

```
#Number of data points
Nd = [10,100]

#Number of coefficients
Nc = [2,5]

#Number of simulations
Nreps = 50

#perform the benchmark
results = benchmark(samplers,simulateRegression,Nd,Nc,Nreps)
```

This benchmark configuration is defined in benchmark_configurations/Vary_Data_Coefs.jl. The configuration functions are defined as follows:

```
 function benchmark(samplers,simulate,Nd,Nc,Nreps=100;Nsamples=2000,Nadapt=1000,delta=.8)
     results = DataFrame()
     for nd in Nd
         for nc in Nc
             benchmark!(samplers,results,simulate,Nreps;Nd=nd,Nc=nc,Nsamples=Nsamples,Nadapt=Nadapt,delta=delta)
         end
     end
     return results
 end

 function pbenchmark(samplers,simulate,Nd,Nc,Nreps=100)
     pfun(rep) = benchmark(samplers,simulate,Nd,Nc,rep)
     reps = setreps(Nreps)
     presults = pmap(rep->pfun(rep),reps)
     return vcat(presults...)
 end
```
The primary difference between this configuration and the other one we have been using is that we now have a for loop nested within another. 

Here is the Turing model:

```
@model AHMCregression(x,y,Nd,Nc) = begin
    B = Array{Real}(undef,Nc)
    B ~ [Normal(0,10)]
    B0 ~ Normal(0,10)
    sigma ~ Truncated(Cauchy(0,5),0,Inf)
    mu = B0 .+ x*B
    for n = 1:Nd
        y[n] ~ Normal(mu[n],sigma)
    end
end
```

For each model it will be important to use the same order of arguments. The simulated data are collected in a NamedTuple and splatted into the call to runSampler as so: `runSampler(s,data...)`. This allows runSampler to work with variable argument numbers. Here is the simulation function:

```
function simulateRegression(;Nd,Nc,β0=1.,β=fill(.5,Nc),σ=1,kwargs...)
    x = rand(Normal(10,5),Nd,Nc)
    y = β0 .+ x*β .+ rand(Normal(0,σ),Nd)
    return (x=x,y=y,Nd=Nd,Nc=Nc)
 end
```
Another important point to make is that the variable names must be consistent across the model instantiations. As far as I know, Stan does not use unicode. So you should change the variable names to B0 and B for the slopes (or you could reparameterize the model so that B0 and B are one vector). Otherwise, calculations such as ess will not work. 

You might have noticed that I used unicode in `simulateRegression`. The reason I used that is we can potentially pass those variables as optional keywords to benchmark if we want to control those values from the top-level script. We could also define a different benchmark configuration where we loop over values of beta0 and beta as a manipulation of the benchmark simulation.

Hopefully this helps you moving forward. My apologies if you already understand these points.  I was not quite sure what issues you were having with the framework.

**Comment by itsdfish** [comment]
Hi Rob-

I have some free time this weekend and next weekend. If you would like, I can finish the remaining two models without too much problem.

**Comment by goedman** [comment]
If you could, that would be great! You are anyway much stronger on the model side.

**Comment by itsdfish** [comment]
Will do!

**Comment by goedman** [comment]
Thanks Chris, I'll study it over the next couple of days. Mainly worked on fixing a bunch of issues with CmdStan last week but it seems to be back on track once v5.1.0 is released.

**Comment by itsdfish** [comment]
No problem. I am also trying to figure out a way to append dataframes with different number of columns. This will allow us run variations of a model with different parameters within the same benchmark (e.g. different subject parameters in a hierarchical model or varying number of coefficients in a regression model). Unfortunately, DataFrames does not appear to have this functionality built in.

**Comment by goedman** [comment]
I guess only a limited set of columns are of interest to compare, e.g. timing related (others, e.g. ESS related, are not appropriate as they are from different models). It looks like it would require multiple DataFrames. Maybe this could be solved by clever join-operations but I'm not sure if the resulting DataFrames become unwieldy.

**Comment by itsdfish** [comment]
Very true. Some comparisons may not make sense or may lot be the primary focus. A few weeks ago I added the mean and 95% credible interval of the parameter estimates to the benchmark output so that we can verify that the parameters are properly recovered (there is a corresponding plot). So this may not be our primary interest, but I think it would be good to have as a sanity check. 

After considerable struggle, I eventually discovered that `vcat` has a `cols` keyword that allows concatenation of dataframes with different columns: `vcat(df1,df2,cols=:union).`

**Comment by goedman** [comment]
Great! That certainly helps and seems simpler than multiple DataFrames. And I had definitely noted some great improvements in the generated graphs!

I do believe Bob made another good point. There is a wealth of interesting info in the MCMCBenchmarks plots, we need to think if and how we want to document the results.

Based on some of the work we've (you mainly) been doing I did make some changes to CmdStan.jl in that I created an option to set the tmp directory in the Stanmodel call (also maybe useful for Windows where you can now store all generated files on a real tmp directory).

Another option added gives access to the stansummary data without displaying the summary itself, e.g. in the Bernoulli example:
```
  stanmodel = Stanmodel(Sample(save_warmup=true, num_warmup=1000, 
    num_samples=2000, thin=1), name="bernoulli", model=bernoullimodel,
    printsummary=false, tmpdir=mktempdir());
```

Using read_summary() now returns a ChainDataFrame with the actual values computed by the  cmdstan binary:
```
julia> summary_df = read_summary(stanmodel)
CmdStan Summary

│ Row │ parameters    │ mean     │ mcse       │ std      │ 5%       │
│     │ Any           │ Any      │ Any        │ Any      │ Any      │
├─────┼───────────────┼──────────┼────────────┼──────────┼──────────┤
│ 1   │ lp__          │ -8.16727 │ 0.0137126  │ 0.748415 │ -9.64046 │
│ 2   │ accept_stat__ │ 0.925802 │ 0.00499892 │ 0.116177 │ 0.683785 │
│ 3   │ stepsize__    │ 1.01018  │ 0.0813839  │ 0.115109 │ 0.846404 │
│ 4   │ treedepth__   │ 1.39837  │ 0.00600126 │ 0.509858 │ 1.0      │
│ 5   │ n_leapfrog__  │ 2.6405   │ 0.170465   │ 1.44049  │ 1.0      │
│ 6   │ divergent__   │ 0.0      │ NaN        │ 0.0      │ 0.0      │
│ 7   │ energy__      │ 8.67329  │ 0.01893    │ 1.04559  │ 7.6949   │
│ 8   │ theta         │ 0.332972 │ 0.00249938 │ 0.131318 │ 0.134172 │

│ Row │ 50%      │ 95%      │ ess     │ n_eff/s │ r_hat      │
│     │ Any      │ Any      │ Any     │ Any     │ Any        │
├─────┼──────────┼──────────┼─────────┼─────────┼────────────┤
│ 1   │ -7.88058 │ -7.64039 │ 2978.82 │ 13254.3 │ 1.00065    │
│ 2   │ 0.974214 │ 1.0      │ 540.117 │ 2403.27 │ 1.01268    │
│ 3   │ 1.10197  │ 1.13322  │ 2.0005  │ 8.90128 │ 3.52072e13 │
│ 4   │ 1.0      │ 2.0      │ 7217.95 │ 32116.4 │ 1.00444    │
│ 5   │ 3.0      │ 7.0      │ 71.4089 │ 317.736 │ 1.02711    │
│ 6   │ 0.0      │ 0.0      │ NaN     │ NaN     │ NaN        │
│ 7   │ 8.33994  │ 10.7643  │ 3050.88 │ 13575.0 │ 1.00076    │
│ 8   │ 0.322173 │ 0.56327  │ 2760.49 │ 12282.9 │ 1.00359    │

julia> summary_df[:theta, :ess]
1-element Array{Any,1}:
 2760.49

```

I'm updating the docs before I release CmdStan v5.1.0 and after that I will start to look more seriously into CmdStan v6 (based on some of Tamas Papp's packages).

**Comment by itsdfish** [comment]
Awesome. It sounds like you are adding some useful features to CmdStan.

I agree. It might be a good idea to add some documentation and include a section with benchmark results from the builtin models. As you mentioned, there is a wealth of information and we could not feasibly display it all. That being that case, it would be nice if there was interactive GUI in which users could explore and plot data in various ways. Unfortunately, I did not find any package of this sort.  Nonetheless, I will look through some of the documentation of the major packages to get some ideas for documenting the results.
