### ISSUE TITLE
Test with reverse auto-diff

### ISSUE THREAD

**Issue by itsdfish** [StatisticalRethinkingJulia/MCMCBenchmarks.jl#20]
Hi Rob-

I noticed that the samplers use different auto differentiation algorithms, which will qualify the conclusions we can draw from the benchmarks. My naive understanding is that forward autodiff is generally faster for problems with a small number of inputs (e.g. parameters or observations) and the opposite is generally true for the reverse method. Here is an example comparing CmdStan and DynamicHMC for 10, 100, 1,000 and 10,000 data points:

[Gaussiansummary_time.pdf](https://github.com/StatisticalRethinkingJulia/MCMCBenchmarks.jl/files/3244840/Gaussiansummary_time.pdf)

I suspect this pattern is due to the choice of auto-diff.
 
At some point, I think we should try to compare CmdStan and DynamicHMC with reverse auto-diff. Do you know the state of reverse autodiff in Julia?

**Comment by goedman** [comment]
Hi Chris,

In one exchange early on about AD someone (I think Tamas, but I'm not sure about that) mentioned that ForwardDiff is slower (maybe less so with small models?) then ReverseDiff but more stable. Other options are Flux and the newer kid on the block is Zygote. I believe Zygote is where Tamas/dHMC would like to go but I don't think it's quite there yet. 

I think (very?) early versions of Stan did not use AD but this was later introduced (at least a couple of years ago by now, you asked about that once). In Bob Carpenter's email he mentioned his interest in AD, so we can also ask him about how this is currently done in Stan, Boost, the Stan Math lib.

But above graph (and we've seen this scalability behavior now a few times) is telling. We can certainly also ask Tamas about this once we think we understand it to the best of our abilities.

I must say I'm quite impressed by what we've already gotten out of mainly your work (the improvement to as() you found, the recent initialization problem and the general benchmarking results).

**Comment by goedman** [comment]
We can try to run DynamicHMC with ReverseDiff, Flux and maybe Zygote?

**Comment by itsdfish** [comment]
That sounds good. I'll try to figure out what is involved in using the various reverse autodiff packages. It would be convenient if autodiff could be selected with a symbol, such as `:Zygote`.

**Comment by itsdfish** [comment]
P.S. In Turing, it is possible to use reverse auto-diff (from ReverseDiff.jl I think)  with the following call:

`Turing.setadbackend(:reverse_diff)`

Using DynamicNUTS, a model that requires about 5 seconds to complete with forward mode requires 355 seconds in reverse mode, or about 71 times longer. Needless to say, that version of autodiff is practically unusable. Hopefully one of the other options is better.

**Comment by goedman** [comment]
Yes, in DynamicHMC you need to use ReverseDiff.jl. But I’m surprised it is that slow, I must have reversed speed and stability of the 2 AD options.

Do we need Revise.jl?

**Comment by itsdfish** [comment]
No. I don't think we do. I'll go ahead and remove unneeded dependencies.

**Comment by trappmartin** [comment]
Yes, the choice of AD makes a big difference (also for HMC sampling in Turing). 

Hong recently did a test with a 250 dimensional multivariate Gaussian distribution in Turing and gets the following results for forward mode AD and for reverse mode AD (Flux.Tracker). I believe once Zygote is stable enough we will integrate Zygote as it should be much faster than Flux.Tracker.

```Julia
julia> Turing.setadbackend(:reverse_diff)
:reverse_diff

julia> chain = sample(mdemo(d, 1), HMC(5000, 0.1, 5)) 
┌ Info: Finished 5000 sampling steps in 26.268800422 (s)
│   typeof(h.metric) = AdvancedHMC.Adaptation.UnitEuclideanMetric
│   typeof(τ) = AdvancedHMC.StaticTrajectory{AdvancedHMC.Leapfrog{Float64}}
│   EBFMI(Hs) = 8304.678836508461
└   mean(αs) = 0.009693583026006005
Object of type Chains, with data of type 5000×252×1 Array{Union{Missing, Float64},3}

julia> Turing.setadbackend(:forward_diff)
:forward_diff

julia> chain = sample(mdemo(d, 1), HMC(5000, 0.1, 5))
┌ Info: Finished 5000 sampling steps in 1908.102999148 (s)
│   typeof(h.metric) = AdvancedHMC.Adaptation.UnitEuclideanMetric
│   typeof(τ) = AdvancedHMC.StaticTrajectory{AdvancedHMC.Leapfrog{Float64}}
│   EBFMI(Hs) = 8263.48476883062
└   mean(αs) = 0.010270009606607896
Object of type Chains, with data of type 5000×252×1 Array{Union{Missing, Float64},3}
```

**Comment by itsdfish** [comment]
Wow. That is a huge difference. Do you have any idea how Zygote performs relative to Stan?

**Comment by goedman** [comment]
I would guess that over time Zygote will get close to AD in C++/Boost/StanMath in both performance and stability. But as Chris Elrod showed in his two demo projects, adding ‘optimized’ functions will be what will make the real difference and for that Julia has advantages. A while ago Hong also showed this in Turing by providing I believe a vectorized Bernoulli.

**Comment by itsdfish** [comment]
Hi @tpapp. Rob and I are interested in exploring reverse AD to improve performance on larger problems. I was wondering if it is possible to use Zygote as the AD for DynamicHMC? Is it a simple drop in or does it require a lot of integration? Thanks!

**Comment by tpapp** [comment]
I have been using Zygote for a few months now, and indeed it is amazing. It is implemented in 

https://github.com/tpapp/LogDensityProblems.jl/blob/master/src/AD_Zygote.jl

since March 2019. DynamicHMC just takes the gradient and it doesn't care where it came from. You just do 
```julia
ADgradient(:Zygote, l)
```
like for any other AD interface. If you encounter problems, please open an issue and I am happy to fix them.

**Comment by itsdfish** [comment]
That is awesome that is simply drops in. Great work! Thanks for the info!
