### ISSUE TITLE
Problems with LBA and Turing

### ISSUE THREAD

**Issue by itsdfish** [StatisticalRethinkingJulia/MCMCBenchmarks.jl#21]
I noticed that at least one of the samplers is not converging with the LBA based on cross-sampler rhat. I believe it is Turing because it generates several numerical errors on most runs. I want to investigate this further and open an issue with Turing if it in fact appears to be the culprit.

**Comment by trappmartin** [comment]
Could you open an issue on this at the Turing repo. Then we can have a look into it.

Thanks!

**Comment by itsdfish** [comment]
Thanks @trappmartin.  The most recent model I added to our test suite may have been problematic too.Tomorrow I will aggregate some notes and open an issue with Turing.

**Comment by itsdfish** [comment]
I opened an issue with [Turing](https://github.com/TuringLang/Turing.jl/issues/840) detailing some of the problems that we have encountered.
