### ISSUE TITLE
Comments Bob Carpenter

### ISSUE THREAD

**Issue by goedman** [StatisticalRethinkingJulia/MCMCBenchmarks.jl#22]
Just so we don't forget:

"Run time charts should almost always be on a log scale. It makes it easy to see the proportional speedup at any point. It looks like CmdStan is faster, but not clear by how much because the chart’s dominated by the slow system (don’t know what those are other than CmdStan).

I would have expected the ESS numbers to follow the R-hat numbers. How are you computing these two things? It looks like you’re not using our most up-to-date R-hat calculations, as things seem to be bounded at the number of draws. The ESS can exceed the number of draws due to anticorrelation. This is common in simple models fit with NUTS because of the way it biases to later draws.

How do you calculate timing?

It wasn’t clear to me where to find the key to which lines meant what in the figures."

**Comment by goedman** [comment]
And a few earlier comments:

"What kind of models and coding in Stan are you doing? I’m particularly interested in things like matrix derivative support and vectorized densities/transforms, etc.

Are you evaluating performance on an effective sample size/second basis? And using Stan’s ESS calculator for everything? Or better, evaluating it for squared error on simulated data for both X and X^2 (to get an idea of performance on standard means and variances of parameters).

For Stan, the performance is pretty much 100% determined by how fast the math library executes derivatives. If you can do that faster than the Stan math library, you can implement HMC/NUTS faster than Stan (assuming you have the dynamic autodiff to handle NUTS!)."

**Comment by itsdfish** [comment]
Is there a way to use Stan's rhat and ess formulas and store them within an MCMCChain object?

**Comment by goedman** [comment]
Hi Chris,

You mean the formulas underlying the actual (C++ coded) computation in the `stansummary` binary?

I believe Cameron has followed these closely in MCMCChains.  There is no way to store these right now, but if useful I'm sure it can be added.

Or is it better to just use the `read_summary()` method in CmdStan.jl as I expect these computations will start to change over the next few months?

Rob

**Comment by itsdfish** [comment]
Sorry. I think I am getting ahead of myself.

I just want to confirm that Stan and MCMCChains uses the same formulas. It does appear, however,  that ESS is truncated at the number of samples, unlike Stan. (running `Chains(randn(10,1,1))` repeatedly never gave a number > 10) So Cameron's implementation might differ in some regard. I looked at his code, but nothing seemed off, e.g.` ess = min(num_samples,ess)`

**Comment by goedman** [comment]
At some point I did make a number of plots to compare stansummary's with MCMCChains values and the followed pretty closely (but not exact). What do you mean by `truncated by the number of samples`? That's in the autocorrelation computation?

**Comment by itsdfish** [comment]
ESS appears to be truncated or bounded at num_samples, such that ESS <= num_samples. However, if there is negative correlation in the chain, it is possible for ESS > num_samples. Bob also noted this:

> It looks like you’re not using our most up-to-date R-hat calculations, as things seem to be bounded at the number of draws. The ESS can exceed the number of draws due to anticorrelation.

I was not able to produce a case in which   ESS > num_samples.

**Comment by itsdfish** [comment]
For future reference, this demonstrates that ess is truncated at nsamples:


```
using MCMCChains

function sim(nsamples)
    cnt = 0
    for i in 1:1000
        chn = Chains(randn(nsamples,1,1))
        ess = describe(chn)[1].df[:ess][1]
        ess > nsamples ? cnt+=1 : nothing 
    end 
    return cnt 
end
```

```
julia> sim(10)
0
```

**Comment by itsdfish** [comment]
It is also possible to see the truncation at Nsamples = 1e3 in the first column of the file linked [here](https://github.com/StatisticalRethinkingJulia/MCMCBenchmarks.jl/blob/master/Examples/Gaussian/results/2019_05_26T06_19_00/results.csv).

**Comment by goedman** [comment]
Yip, and the sigma_ess as well.

I've opened an issue on MCMCChains to see it Cameron immediately sees why this might happen.

**Comment by itsdfish** [comment]
Bob noted that the biggest performance determinant is the computation of the gradients and derivatives. If that is true, I wonder what you think of this:  


```
using Distributions, Zygote,ForwardDiff,BenchmarkTools,Tracker

function g(x)
   return logpdf(Normal(x[1],x[2]),x[3])
end
x = [0,1,1]
println("Normal")
@btime Zygote.gradient($g, $x)
@btime Tracker.gradient($g, $x)
@btime ForwardDiff.gradient($g, $x)


function g1(x)
   return logpdf(Cauchy(x[1],x[2]),x[3])
end
x = [3.,1.,.4]
println("Beta")
@btime Zygote.gradient($g1, $x)
@btime Tracker.gradient($g1, $x)
@btime ForwardDiff.gradient($g1, $x)

function g2(x)
   return -x[1]+x[2]*log(x[1])-log(factorial(x[2]))
end
x = [3.,1.]
println("Poisson")
@btime Zygote.gradient($g2, $x)
@btime Tracker.gradient($g2, $x)
@btime ForwardDiff.gradient($g2, $x)
```
Results: 

```
Normal
  11.073 μs (159 allocations: 5.42 KiB)
  3.002 μs (132 allocations: 4.28 KiB)
  366.286 ns (3 allocations: 384 bytes)
Beta
  3.511 μs (69 allocations: 2.30 KiB)
  2.948 μs (140 allocations: 4.48 KiB)
  396.100 ns (3 allocations: 384 bytes)
Poisson
  1.182 μs (47 allocations: 1.67 KiB)
  3.013 μs (142 allocations: 4.50 KiB)
  448.472 ns (3 allocations: 272 bytes)

```

**Comment by goedman** [comment]
Good question. Could it be that these functions are too simple to show the benefits of Flux and Zygote?

**Comment by itsdfish** [comment]
I was wondering the same thing. I found recently posted issues showing performance problems with less trivial examples. [Here](https://github.com/FluxML/Flux.jl/issues/822) and [here](https://github.com/FluxML/Flux.jl/issues/815).
