### ISSUE TITLE
Add Tests

### ISSUE THREAD

**Issue by itsdfish** [StatisticalRethinkingJulia/MCMCBenchmarks.jl#27]
Hi Rob-

I started writing some basic tests and thought I should coordinate with you. Here is a tentative list of tests:

1. Tests of the generative functions, which will include tests of output types and sufficient statistics if available.
2. Tests of plots to make sure they run at the very least. I'm not sure if there is a way to test the content of the plots. 
3. A fast test of each sampler and model. We can test the results dataframe columns and possibly test the HDI of the parameter estimates. 

My goal is to make the tests as quick as possible by using a small sample size and a single rep. Aside from these three basic categories, do you recommend any other tests? Next weekend I should have time to dedicate to this. Do you want to tackle any of it? No pressure either way. I just want to make sure we do not duplicate work.

**Comment by itsdfish** [comment]
Hi Rob-

I add some initial tests, which cover the generative models, the mean posterior estimates and cross sampler rhats for each model and sampler. The LBA fails the rhat tests, which isn't entirely surprising. There are similar problems with the multiple regression test. The Poisson regression tests were difficult because the parameter estimates were noisy. Using large sample sizes was not a viable solution because Turing and DynamicHMC were very slow on this model. 

Let me know if you have any feedback or additions. At some point, it might be good to test some of the component functions so that failures will be more diagnostic.

**Comment by goedman** [comment]
Hi Chris,

Just testing it right now, but looks good.

I'll add the before_install section to .travis.yml to have cmdstan available. I've also added Distributions to Projects.toml.

What is the intention of the ```@eval module $(Symbol("Test_", t))```? Just never seen that.

As you mention, some estimates are pretty noisy, we could for now widen those test ranges. I'll see if that makes it pass on my system first and then check Travis (after merging).

Rob

**Comment by itsdfish** [comment]
Yeah. I think you are right. Even though expanding the tolerances will make the tests less informative, it is still better than nothing. As the packages become more performant, we can make the tests more diagnostic. 



> What is the intention of the `@eval module $(Symbol("Test_", t))`? Just never seen that.

I think so. I borrowed this code from Distributions.jl. It essentially creates a new module and evaluates the code so that variables do not clash in the outer scope.

**Comment by goedman** [comment]
As long as the tests show the code runs I think we’re ok for now. Maybe at some point we can set the seed values.

**Comment by itsdfish** [comment]
Rob, I added additional tests for plots and set a random seed so that we should not get random failures. Everything appears to run locally, except cross-sampler Rhat for the LBA and regression are off. I suspect it is a problem with Turing but I will have to investigate. 

One question I have is whether creating and deleting the tmp folder create problems for remote testing?

**Comment by goedman** [comment]
Hi Chris, what do you mean by remote testing? In general you can always delete them once you have read in the samples and created the cmdstan summary file.

I just added some updates to .travis.yml, Project.toml & Manifest.toml. See how far it gets on Travis.

**Comment by itsdfish** [comment]
Hey Rob. Yeah. I'm still learning the terminology. I was referring to Travis. I wasn't sure if there would be a problem with creating files on that system. 

Will the failed tests be a problem? I think Test.jl has a way to skip tests that are failing temporarily.

**Comment by goedman** [comment]
The weird thing is on my system (OSX) it fails on several regression tests (in the end it tells me 7 passed, 5 failed).

But on Travis it fails much earlier, where we are adding a column to a DataFrame:
```
Gaussian Tests : Error During Test at /home/travis/build/StatisticalRethinkingJulia/MCMCBenchmarks.jl/test/Gaussian_Tests.jl:3
  Got exception outside of a @test
  MethodError: no method matching getindex(::DataFrame, ::typeof(!), ::Symbol)
  Closest candidates are:
    getindex(::DataFrame, !Matched::Integer, ::Symbol) at /home/travis/.julia/packages/DataFrames/CZrca/src/dataframe/dataframe.jl:327
    getindex(::DataFrame, !Matched::AbstractArray{T,1} where T, ::Union{Signed, Symbol, Unsigned}) at /home/travis/.julia/packages/DataFrames/CZrca/src/dataframe/dataframe.jl:337
    getindex(::DataFrame, !Matched::Colon, ::Union{Signed, Symbol, Unsigned}) at /home/travis/.julia/packages/DataFrames/CZrca/src/dataframe/dataframe.jl:358
    ...
  Stacktrace:
   [1] addColumns!(::DataFrame, ::Chains{Float64,Missing,NamedTuple{(:internals, :parameters),Tuple{Array{String,1},Array{String,1}}},NamedTuple{(:hashedsummary,),Tuple{Base.RefValue{Tuple{UInt64,Array{ChainDataFrame,1}}}}}}, ::DataFrame, ::Symbol) at /home/travis/build/StatisticalRethinkingJulia/MCMCBenchmarks.jl/src/MCMCBenchmarks.jl:309
   [2] #updateResults!#50(::Base.Iterators.Pairs{Symbol,Real,NTuple{4,Symbol},NamedTuple{(:Nsamples, :Nadapt, :delta, :Nd),Tuple{Int64,Int64,Float64,Int64}}}, ::Function, ::CmdStanNUTS{Stanmodel}, ::Tuple{Chains{Float64,Missing,NamedTuple{(:internals, :parameters),Tuple{Array{String,1},Array{String,1}}},NamedTuple{(:hashedsummary,),Tuple{Base.RefValue{Tuple{UInt64,Array{ChainDataFrame,1}}}}}},Float64,Int64,Float64,Base.GC_Diff}, ::DataFrame) at /home/travis/build/StatisticalRethinkingJulia/MCMCBenchmarks.jl/src/MCMCBenchmarks.jl:201
```

It definitely passes Gaussian, SDT, Poisson on my system.

**Comment by itsdfish** [comment]
I modified the tests so that everything passes as long as the benchmarks run. When the packages stabilize and improve in speed, I can perform a more stringent parameter recovery test to ensure the models are estimating parameters as expected.
