### ISSUE TITLE
Inconsistency between preconditoning matrix adaptation methods

### ISSUE THREAD

**Issue by xukai92** [StatisticalRethinkingJulia/MCMCBenchmarks.jl#29]
By default, CmdStan uses diagonal preconditoning matrix adapation (correct me if I'm wrong)

```julia
julia> CmdStan.Hmc()
CmdStan.Hmc(CmdStan.Nuts(10), CmdStan.diag_e(), 1.0, 1.0)
```

while Turing uses dense preconditoning matrix adapation by default. So I guess it should be set to the same while benchmarking. 

This is the reference code I use to set for both:

```julia
stanmodel = Stanmodel(
    name = "normstanmodel", model = normstanmodel, nchains = 4,
    Sample(num_samples = Nsamples-Nadapt,
        num_warmup = Nadapt,
        # adapt = CmdStan.Adapt(engaged=false),
        adapt = CmdStan.Adapt(delta=0.8),
        save_warmup = false,
        algorithm=CmdStan.Hmc(;
            engine=CmdStan.Nuts(),
            # engine=CmdStan.Static(; int_time=0.1),
            # metric=CmdStan.unit_e,
            metric=CmdStan.diag_e,
            # metric=CmdStan.dense_e,
            stepsize=1.0,
            # stepsize=0.01,
            stepsize_jitter=0.0)
    )
);

  chn = mapreduce(x->sample(model(data["y"]),
        Turing.NUTS(
            Nsamples, Nadapt, 0.8;
            max_depth = 10,
            init_ϵ = 1.0,
            # metricT=AHMC.UnitEuclideanMetric,
            metricT=AHMC.DiagEuclideanMetric,
            # metricT=AHMC.DenseEuclideanMetric,
        ),
        # Turing.HMCDA(
        #       Nsamples, Nadapt, 0.8, 0.1;
        #       init_ϵ=1.0,
        #       # metricT=AHMC.UnitEuclideanMetric,
        #       metricT=AHMC.DenseEuclideanMetric,
        # ),
        # Turing.HMC(
        #     Nsamples, 0.01, 10
        # ),
        # Turing.DynamicNUTS(
        #     Nsamples - Nadapt
        # ),
      ),
      chainscat, 1:4)
```

Maybe Turing.jl should also use diagonal as default because it seems to be better in a lot of cases. Is this what you find in your experience?

**Comment by xukai92** [comment]
PS: I also disabled the noisy step size in Stan by `stepsize_jitter=0.0`. The only reason for me to do so is for a fair comparison as AHMC doesn't implement it. But we probably don't want to do this in thie benchmark suite, and AHMC will have it soon.

**Comment by itsdfish** [comment]
Thanks for pointing that out. In the documentation, I will have to be clear about whether the settings are equated or left at their defaults. In either case, I will add some default values and a way to overwrite the default configuration.

**Comment by itsdfish** [comment]
I'm not very familiar with the different configurations. Maybe @goedman has some advice? In the worst case scenario, we can benchmark different configurations to decide.

**Comment by goedman** [comment]
Chris, not quite sure what you are asking here. After running a simulation, stanmodel.command contains the exact command line used to run cmdstan and all settings (including the defaults).
Maybe we want to store those?

The Stan folks have spent a lot of time tuning these defaults across the board, but for a single benchmark we now have tools to evaluate these better.

As I said, not quite sure how to answer this.

**Comment by itsdfish** [comment]
I think your response answers my question. It seems like it is worth adding the ability to modify the NUTS configuration since Stan developers have optimized the configurations.

**Comment by itsdfish** [comment]
@xukai92, it looks like Rob's recommendation is to use a diagonal preconditioning matrix for adoption because Stan has tested this extensively. I'm going to close this issue for now and not make any changes. Adding the ability to modify the NUTS configuration would not be too difficult, but the current complication is that the preconditioning matrices have different names in each package. However, if you or Rob find this capability useful, I can think of some workarounds (probably something like conditionals to map a generic name to package specific names).

**Comment by goedman** [comment]
Clearly I hadn't read the whole thread carefully. But Kai's earlier question is a very valid one. I have never experimented with this, but the fact that it is included in the cmdstan parameter set means it must be relevant in some cases although I don't think we have to deal with this right now.

**Comment by xukai92** [comment]
@itsdfish, thanks. @yebai and I also decided to make diagonal preconditioning as default. So after the incoming marjor release Turing and Stan's default sampler shall match, except from the step size jittering, for which I already implemented but made it disabled as default due to https://github.com/stan-dev/stan/issues/2183.

Also bear in mind that DHMC uses dense preconditioning as default.

**Comment by goedman** [comment]
@xukai92 you might have seen [this](https://discourse.mc-stan.org/t/request-for-volunteers-to-test-adaptation-tweak/9532) discussion but just in case. I ran it for a couple of smaller models and saw no huge difference but want to test it on LBA later today.

**Comment by itsdfish** [comment]
Excellent. Thanks for the update. Now Turing and Stan should be more comparable. 

@goedman, I was thinking about changing the preconditioning matrix for DynamicHMC to diagonal for our tests if possible. Do you have any objections?

**Comment by goedman** [comment]
Not really, but I would probably ping @tpapp as well.

**Comment by tpapp** [comment]
I think diagonal is a good compromise. Off-diagonal values are occasionally adapted to spurious values; the sampler can usually cope but it degrades performance.
