### ISSUE TITLE
Standardize names for cross sampler rhat

### ISSUE THREAD

**Issue by itsdfish** [StatisticalRethinkingJulia/MCMCBenchmarks.jl#33]
Hey Rob-

While developing tests, I noticed an error in my cross sampler rhat calculation. The code does not standardize the names for vector parameters, which currently could be parm.1 or parm[1]. I was wondering if you have any advice for changing the parameter names. I cannot figure out how to change only the parameter names.

```
using MCMCChains 

chn = Chains(rand(10,2,1))
chn = set_section(chn,Dict(:internals=>["a","b"]))
println(chn)
```
If you don't have any ideas, I might have to open an issue with MCMCChains.

**Comment by goedman** [comment]
Hmm, my favorite topic ...

Once constructed you can’t chains the names (immutable part of AxisArrays), just the name_map. Your best bet is extracting the data using chn.value.data and the names with names(chn) and construct a new Chains object.

**Comment by itsdfish** [comment]
Thanks. That is the only feasible way to do it evidently. I have something that will work.
