### ISSUE TITLE
Fix DataFrame Deprecations

### ISSUE THREAD

**Issue by itsdfish** [StatisticalRethinkingJulia/MCMCBenchmarks.jl#34]
The newest version of DataFrames has a lot of deprecations. I will try to fix those today. The most annoying part is that they removed the promotion rule for assigning scalars to a column. For example, 

```
x = .3
df[!,:a] = [x]

```
However, if x can be a scalar or vector, assignment is inelegant without promotion. Just a FWI.

**Comment by goedman** [comment]
Yes, was bitten by these warnings as well. Not very clear which module they actually come from. Very annoying

**Comment by itsdfish** [comment]
Fortunately, it looks like the folks at DataFrames will be restoring the functionality I noted above. So that should make things cleaner and more flexible. I'm going to reopen the issue so I can make updates when changes to DataFrames are merged.

**Comment by goedman** [comment]
The problem I ran into was related that in the past you could say `df[:col_name]`, now you'll get a warning and need to use `df[!:, :col_name]`. Luckily a simple change across many files.

**Comment by itsdfish** [comment]
Yeah. The syntax is a little weird, but it seems to be a clever way to denote copy vs. mutate. They may not be adding those syntax changes I noted in the previous comment because it introduces an inconsistency somewhere. I"ll keep an eye on it.

**Comment by itsdfish** [comment]
Now it looks like DataFrames will not support adding scalars to empty DataFrames. I'll close this issue, as no changes to our code are necessary.
