### ISSUE TITLE
Does not run with low Nsamples and Nadapt

### ISSUE THREAD

**Issue by itsdfish** [StatisticalRethinkingJulia/MCMCBenchmarks.jl#35]
Returns an empty array for some reason.

**Comment by itsdfish** [comment]
It looks like with low sample sizes certain metrics, such as lp_eps, do not compute reliably. I'm guessing this is just a numerical stability problem, but if you think this needs reported to MCMCChains, let me know.

**Comment by goedman** [comment]
I remember a discussion on MCMCChains about this, I believe it was decided that below 200 draws or so the results are not trustworthy.

**Comment by itsdfish** [comment]
Thanks. That explains it.
