### ISSUE TITLE
Pin DynamicHMC and LogDensityProblems

### ISSUE THREAD

**Issue by itsdfish** [StatisticalRethinkingJulia/MCMCBenchmarks.jl#36]
We will need to pin DynamicHMC and LogDensityProblems while it is being revised. See Tamas's [page](https://tamaspapp.eu/post/2019-07-25-psa-dhmc-api-change/) for info. 

Once I figure out how to do this, hopefully the docs will update.

**Comment by goedman** [comment]
Hi Chris,

```

(v1.3) pkg> ?pin
  pin pkg[=uuid] ...

  Pin packages to given versions, or the current version if no version is
  specified. A pinned package has its version fixed and will not be upgraded or
  downgraded. A pinned package has the symbol ⚲ next to its version in the status
  list.

  Examples

  pkg> pin Example
  pkg> pin Example@0.5.0
  pkg> pin Example=7876af07-990d-54b4-ab0e-23690620f79a@0.5.0

```
I just removed LogDensityProblems, upgraded DynamicHMC and reinstalled LogDenssity problems once I figured out what `LogDensityProblems = "^0.8.3" in the [Compat] section in Project.toml really meant.

My issue was that I had upgraded clip-03.jl in chapter 9 of StatisticalRethinking to used the new LogDensityProblems setup so to run and test that I do need LogDensityProblems v"0.9.0".

**Comment by itsdfish** [comment]
Thanks Rob. I added the constraints to the Compat section of the Project.toml file, but it still [crashed](https://travis-ci.org/StatisticalRethinkingJulia/MCMCBenchmarks.jl/jobs/566156259). It looks like the constraints couldn't be mutually satisfied.  Do you think that means I need to remove the line containing `LogDensityProblems = "6fdf6af0-433a-55f7-b3ed-c6c6e0b8df7c"`?

**Comment by goedman** [comment]
It is tricky. That line should be removed if you do ‘rm LogDensityProblems’ when MCMCBenchmarks is activated as project. I’m not on my laptop, so it is difficult to send better instructions. Should be home in about an hour.

**Comment by itsdfish** [comment]
Thanks Rob. I tried removing the line with `rm LogDensityProblems`, but that didn't work. Removing it manually didn't fix the error on Travis. Strangely, it works fine on my system with the change.

**Comment by goedman** [comment]
I did an update from the repo to my system and noted LogDensityProblems was missing from the [deps] section on Github. Added it back in.

Project.toml can't have a [compat] line for a package not in either [deps] or [extras].

**Comment by goedman** [comment]
The initial step now runs (no tests of course, but it concludes).

**Comment by goedman** [comment]
Doc step failed on a typo in the file name functions..md. Fixed that and resubmitted.

**Comment by itsdfish** [comment]
I found other double dots. I'm not sure how that happened. Strange. Well, I pushed those fixes. I wouldn't be surprised if there are more problems with the docs.

**Comment by itsdfish** [comment]
Thanks for your help Rob. It looks like everything is working now. I will finish up the documentation over the rest of the week.

**Comment by goedman** [comment]
Hi Chris,

Sounds great! Docs is a slow process of improvements over time ...

Just for future reference, in the case of StatisticalRethinking, which currently needs LogDensityProblems v"0.9.0", I start Julia  with:
```
julia13 --project=~/.julia/dev/StatisticalRethinking/
```
It then runs Julia using the project's Project.toml/Manifest.toml.

Rob
