### ISSUE TITLE
How are keyword parameters passed

### ISSUE THREAD

**Issue by xukai92** [StatisticalRethinkingJulia/MCMCBenchmarks.jl#37]
When I was using the code for benchmarking I got confused on how keyword parameters are actually used to construct the sampler.

E.g. in https://github.com/StatisticalRethinkingJulia/MCMCBenchmarks.jl/blob/master/Models/Hierarchical_Poisson/Hierarhical_Poisson_Models.jl#L13, the target acceptance rate is 0.85 but in https://github.com/StatisticalRethinkingJulia/MCMCBenchmarks.jl/blob/master/Examples/Hierarchical_Poisson/Hierarchical_Poisson_Example.jl#L53 it's set again to 0.8.

I believe the 0.85 is override by the 0.8 somehow. How does it actually works?

**Comment by itsdfish** [comment]
Sorry about that. I can see how that is confusing. The value of .85 is overridden by .80. The pertinent lines of code are [here](https://github.com/StatisticalRethinkingJulia/MCMCBenchmarks.jl/blob/7186de79739c7fd9d2bb78f41ebe786bc81591af/src/core_benchmarking.jl#L58) and [here](https://github.com/StatisticalRethinkingJulia/MCMCBenchmarks.jl/blob/7186de79739c7fd9d2bb78f41ebe786bc81591af/src/core_benchmarking.jl#L200).  If you leave this issue open, I will change it to reduce confusion. In any case, the values in `options` will be the values that are ultimately used.

**Comment by itsdfish** [comment]
We should have better documentation soon. I ran into some issues with the documentation because I haven't figured out how to test it locally.

**Comment by xukai92** [comment]
I see. Thanks for you quick response!

PS: I'm working on the reported issue on low ESS of the Hierarchical Poisson model now - will update there on you how it goes.

**Comment by itsdfish** [comment]
Great. Thanks for keeping me in the loop.
