### ISSUE TITLE
Model for DynamicHMC doesn't use truncated distribution

### ISSUE THREAD

**Issue by xukai92** [StatisticalRethinkingJulia/MCMCBenchmarks.jl#38]
It seems to me that we also need `Truncated` here:  https://github.com/StatisticalRethinkingJulia/MCMCBenchmarks.jl/blob/master/Models/Hierarchical_Poisson/Hierarhical_Poisson_Models.jl#L78

**Comment by itsdfish** [comment]
Good catch! I will push the fix shortly.
