### ISSUE TITLE
issues with addColumns!

### ISSUE THREAD

**Issue by itsdfish** [StatisticalRethinkingJulia/MCMCBenchmarks.jl#4]
Hi Rob-

I noticed two issues with `addColumns!`. I have a fix but didn't have enough time to test it before work.  So I refrained from pushing it to master. I just want to let make you aware of the issues and that I will have a fix soon. 

1. CmdStan and Turing have different naming conventions for vector parameters. CmdStan uses` p.1, p.2 ...` whereas Turing uses ` p[1], p[2] ...`. This was a simple fix.
 
2. As shown below,  values appear to be sorted in dataframe but the `chain.name_map.parameters` are not sorted. This will be an easy fix too. However, I was wondering if the ordering is supposed to be different or whether the mapping refers to something internal rather than the dataframe.

```
│ Row │ parameters │ mean     │ std       │ naive_se    │ mcse       │ ess     │ r_hat   │
│     │ Symbol     │ Float64  │ Float64   │ Float64     │ Float64    │ Any     │ Any     │
├─────┼────────────┼──────────┼───────────┼─────────────┼────────────┼─────────┼─────────┤
│ 1   │ A          │ 0.776155 │ 0.129019  │ 0.00333127  │ 0.0207494  │ 23.1517 │ 1.05529 │
│ 2   │ k          │ 0.225742 │ 0.124405  │ 0.00321214  │ 0.0166416  │ 60.8117 │ 1.00028 │
│ 3   │ v[1]       │ 2.07559  │ 0.418119  │ 0.0107958   │ 0.0640924  │ 52.0934 │ 1.01428 │
│ 4   │ v[2]       │ 2.85196  │ 0.462519  │ 0.0119422   │ 0.0717971  │ 53.4414 │ 1.01095 │
│ 5   │ τ          │ 0.284755 │ 0.0282793 │ 0.000730168 │ 0.00344351 │ 67.6888 │ 1.00439 │
```

```
chain.name_map.parameters
5-element Array{String,1}:
 "A"   
 "τ"   
 "v[1]"
 "k"   
 "v[2]"
```

**Comment by goedman** [comment]
Hi Chris,

As far as item 1 is concerned, yes, only the last couple of months this issue has started to bother me while working with different mcmc frameworks. And neither is easy to use as a Symbol. I have been thinking of simply starting to use var_i. In MCMCBenchmarks we use sampler for mcmc option, I wonder if that could create a problem in the future (if we ever want to go beyond NUTS).

And your item 2 has also bothered me right from the start. I don’t understand what problem AxisArrays solve but thoroughly dislike them. What I learned from Cameron is to use names(chain), that will give you the right order and is what I used when initially working on the  Array and DataFrame constructors in MCMCChains. Yesterday it bit me again as I wanted to merge (chainscat) chains from different mcmc options. In the DataFrame constructor I used the name_map to get the sections and sorted names() to list the parameters within sections.

**Comment by goedman** [comment]
Actually I'm ok with how you named entities in LBA, like LBA_Models. If we are consistent, or at least one form of it, we could use Turing_NUTS, Turing_dNUTS, CmdStan_NUTS, Turing_aNUTS, DynamicHMC_NUTS (or dHMC_NUTS, otherwise gets pretty long)?

For chains I use chn_t, chn_s, chn_d although that is not as complete as above sampler names, but that is ok.

You're use of AddColumns is quite handy as well. E.g. in the Chains object to DataFrame constructor, if I don't want the use the default `append_chains=true` setting I could add a column with the chain number (instead of the current `append_chains=false` and getting an array of DataFrames back) or working with chains from multiple samplers we can add a column with that sampler. From then on we could use `by`, Query.jl, etc.

**Comment by goedman** [comment]
Turing returns a[1], stansummary does that as well (although cmdstan's .csv files do not), DynamicHMC returns NamedTuples which have to be processed anyway (but do contain all info to do this well), so maybe we should go that route. I can catch the `a.1` like names in CmdStan's read_samples and convert them to `a[1]`. It just means that we'll have to use a slightly longer selection forms:
```
ss = read_summary(stanmodel, ProjDir)
ss[[Symbol("a[1]")], [:ess, :r_hat]]
```
vs.
```
ss = read_summary(stanmodel, ProjDir)
ss[[:a_1], [:ess, :r_hat]]
```
or we can request the option to use Strings in ChainDataFrames.

**Comment by goedman** [comment]
To get the LBA example proceed a bit further, I had to add a `args...` argument to simulateLBA() as you're passing in keyword arguments like `Nsamples=2000`. That gets me to the `Column names do not match` point.

**Comment by itsdfish** [comment]
Great. Thanks Rob. I will fix the column issue once I return home.

The main problem I was with DynamicHMC was that it was upon initialization. For example if you run:

```
using MCMCBenchmarks,Revise

include("../../Models/LBA_Models.jl")
include("LinearBallisticAccumulator.jl")
Random.seed!(551158015)
data = simulateLBA(;Nd=100)
runSampler(DHMCNUTS(sampleDHMC,2000),data)
```

the code will crash and output:

```
ERROR: DomainError with [0.507015, 0.948383, -0.953634, -0.655427, 0.0256312, -1.34369]:
Starting point has non-finite density.
```

**Comment by itsdfish** [comment]
This should be fixed now. Everything is converted to p[1], but if you prefer p.1, feel free to open.
