### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by itsdfish** [StatisticalRethinkingJulia/MCMCBenchmarks.jl#46]
Hey Rob, is there anything I need to do in order to create a new version aside from making an issue and [tagging](https://github.com/StatisticalRethinkingJulia/MCMCBenchmarks.jl/issues/15) the registrar?

**Comment by goedman** [comment]
Not really, just register it after making sure the version in Project.toml is the new version. It needs to complete the Travis build to be eligible for merging.

**Comment by goedman** [comment]
Looking at the last Travis run, for now, we might have to disable the testing to ensure the Travis build stage passes, at least until DynamicHMC 2.0 is released.

**Comment by itsdfish** [comment]
Everything passes now. Let's give it a try.

**Comment by itsdfish** [comment]
@JuliaRegistrator register() MCMCBenchmarks v0.5.0
