### ISSUE TITLE
Add subdirs to Examples & Models to store the benchmarks?

### ISSUE THREAD

**Issue by goedman** [StatisticalRethinkingJulia/MCMCBenchmarks.jl#5]
E.g.:

Examples
  Gaussian
  LinearRegression
  LBA
  Multilevel1 (m10.4)
  Multilevel2 (m12.6)
  ...

and same for Models?

Should we uses single word snake naming (for anyone on Windows)?

**Comment by itsdfish** [comment]
Yeah. I was about to propose using subdirectories for each model. Let's do that.

For naming conventions, I think single word or _ would work. I'll let you pick.
