### ISSUE TITLE
Added CompatHelper to all packages in StatisticalRethinking

### ISSUE THREAD

**Issue by goedman** [StatisticalRethinkingJulia/MCMCBenchmarks.jl#52]
Hi Chris,

After adding this to all other packages, I also updated MCMCBenchmarks. 

If a package minor bound is updated, CompatHelper will generate a PR and test the PR. We still have to merge this PR.

Hope this is ok.

Rob

**Comment by itsdfish** [comment]
Sounds like a great idea. Thanks!
