### ISSUE TITLE
Domain error for LBA using DynmaicHMC

### ISSUE THREAD

**Issue by itsdfish** [StatisticalRethinkingJulia/MCMCBenchmarks.jl#6]
I believe there is an error in the parameter bounds for the LBA model.  I cannot figure out how to fix it. 

This will produce the error:

```
using MCMCBenchmarks,Revise

include("../../Models/LBA_Models.jl")
include("LinearBallisticAccumulator.jl")
Random.seed!(551158015)
data = simulateLBA(;Nd=100)
runSampler(DHMCNUTS(sampleDHMC,2000),data)
the code will crash and output:
```

```
ERROR: DomainError with [0.507015, 0.948383, -0.953634, -0.655427, 0.0256312, -1.34369]:
Starting point has non-finite density.
```

Here are the bounds:

v is an array and each element can range from -Inf to Inf

A is a Float64 ranging from 0 to  Inf

k is a Float64 ranging from 0 to Inf

tau is a Float64 ranging from 0 to to a positive number that is data dependent. However, I could accommodate 0 to Inf.

Here is what I have in the code: 

```
problem_transformation(p::LBAProb) =
as((v=as(Array,Nc),A=asℝ₊,k=asℝ₊,tau=asℝ₊),)
```

**Comment by goedman** [comment]
Looking at the DynamicHMC code, it happens on the side of the energy calculations to figure out the leapfrog step size. I don't think (but not 100% sure) that is directly related to the scaling of the input variables. Let me try the CmdStan version again, energy calculations should be similar. Earlier I did see quite a few informational messages showing up.

**Comment by itsdfish** [comment]
Thanks Rob. Among the 10 or so times I ran the CmdStan version, I only encountered the message below once:

```
Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
Exception: Exception: Exception: Phi: x is -nan, but must not be nan!  (in '/home/dfish/.julia/dev/MCMCBenchmarks/Examples/LBA/tmp/CmdStanLBA.stan' at line 40)
  (in '/home/dfish/.julia/dev/MCMCBenchmarks/Examples/LBA/tmp/CmdStanLBA.stan' at line 70)
  (in '/home/dfish/.julia/dev/MCMCBenchmarks/Examples/LBA/tmp/CmdStanLBA.stan' at line 118)

If this warning occurs sporadically, such as for highly constrained variable types like covariance matrices, then the sampler is fine,
but if this warning occurs often then your model may be either severely ill-conditioned or misspecified.
```

**Comment by goedman** [comment]
Hi Chris,

Overnight it looks like it completed a single chain for CmdStan. That is progress! It produced about 10 warnings, but I'm not sure in which runs (10, 100 or 500 samples). Need to figure out what's happening with the tmp directory, for some reason it ended up in my home dir.

Will next try to run the Turing runs.

Rob

**Comment by itsdfish** [comment]
Rob-

Thanks for the update. As far as I can tell, it works with Turing but I have not let it run through the entire benchmark process yet because its very slow unfortunately.

**Comment by goedman** [comment]
Thanks Chris,

Definitely takes time! But what I slowly started to suspect, my 'normal` work laptop is getting too full and as a consequence is getting pretty slow. Should have bought the 1TB solid state memory version.

Also, my time has been a bit scattered this week (often the case the months we live in DC), which makes it harder to make real progress. The fact that I'm trying to understand the framework, the LBA model and the DynamicHMC issue(s) does not help either :-)

My plan to remedy this is to create a very simple (fast) model, like Bernoulli (or the Gaussian example with fewer observations), and create a complete test suite in runtests.jl. And add some utilities to after the fact create e.g. the stansummary etc. Maybe the tail end of the the examples (the plotting) could become another utility function if we can pass in the parameters of interest. I also like to mix in the multi-sampler R_hat computations. That allows us to compare those results with separate 4 chains runs in the samplers (most likely CmdStan for now?).

Given that LBA runs on your system (and at least 2 versions on mine), should we merge that to master and move the Gaussian example also to a separate subdirectory?

**Comment by itsdfish** [comment]
I strongly recommend a solid state hard drive if you don't have one already. I will never go back to the old type.

I have added subdirectories for each model on master. I can merge the LBA when I return home.

But if you have any ideas for getting the LBA to work with DynamicHMC, I would be grateful.

**Comment by goedman** [comment]
We need Tamas' help for this. For this we need a MWE (your small script) and also a MWE CmdStan version + results. That was 1 reason I was pushing to get the CmdStan version to work (which it does now a very fast on my other system).

**Comment by goedman** [comment]
Yes, I would never go back to non-solid state memory. When I bought the 13" (easier to travel with) I opted for the 0.5TB and I don't think it is extendable. My other machine I added memory myself and thus although it is quite a bit older, it now runs faster!

**Comment by itsdfish** [comment]
Sounds good.  I am in the process of adding a signal detection model, which should be more tractable. I will wait to put together a MWE for Tamas once that is finished in case I encounter another problem with DynamicHMC.

**Comment by goedman** [comment]
Didn't we already encounter this problem in the Gaussian example. I wonder if it is new, as I never saw it while developing the StatisticalRethinking models.

**Comment by itsdfish** [comment]
Hmmm. I don't recall encountering any errors with DynamicHMC for the Gaussian problem. We do have a problem with DynamicNUTS crashing due to numerical errors however.

**Comment by goedman** [comment]
Correct, I think we had a problem while using the user defined pdf() and/or logpdf(). That went away with Normal().

**Comment by itsdfish** [comment]
I figured out the issue with the LBA and SDT models. For my future reference, the fix for the LBA is 

```
 problem_transformation(p::LBAProb) =
  as((v=as(Array,asℝ₊,Nc),A=asℝ₊,k=asℝ₊,tau=asℝ₊))
```

Without `v=as(Array,asℝ₊,Nc)`, TruncatedNormal produces an infinite starting density. 

In the SDT model, change Nsamples to nsamples. This is an easy fix, but unfortunately it was difficult to identify due to an ambiguous error message.

**Comment by goedman** [comment]
Hi Chris,

Got the Gaussian_Example.jl to work in the osx_test branch.

What is the difference between Gaussian_example.jl and Gaussian_Parallel_Example.jl, both in the Gaussian_Parallel directory?

Is there a reason you kept benchmark_configurations as a directory outside the src directory? In the osx_test branch I've exported the 3 functions in there from MCMCBenchmarks.

I encounter a problem if I leave the tmp directory intact between runs. So right now I delete it.

Importing source files such as the ..._Models.jl is probably better done using pathof(MCMCBenchmarks) vs, ProjDir relative (as normally that would be outside the package).

I'm running into a weird problem with LinearRegression (clearly unfamiliarity with the framework) but on your system all your examples work (so I can test the osx_test mods on those as well?

Finally, in the ..._Examples.jl you set `cd(pwd)` just below the `#pyplot()` line. Is that needed on linux?
Osx objects against the `pwd` in there and I also wonder where you set that variable.

**Comment by goedman** [comment]
On your system, is addprocs(n) cumulative? On my system if I don't restart Julia I end up with many more props. Is the idea to always add 4 cores (given the optimization (13,13,12,12) you mentioned earlier)?

**Comment by itsdfish** [comment]
Hey Rob-

Regarding your first question, I renamed  Gaussian_example.jl to Gaussian_Parallel_Example.jl to make it distinct from the version in Gaussian_Example. In fact, I was thinking about making a parallel counterpart to each of the examples we have, and putting them in the same folder. For example, Gaussian_Example.jl and Gaussian_Parallel_Example.jl will be in the same folder, Gaussian. 

The reason I put the `benchmark` and `pbenchmark` functions in benchmark_configurations is to store different versions of benchmark. For example, if we want to vary Nd and some other variable, such as delta, we could have another file benchmark_configurations/Vary_Nd_delta.jl, which would house those versions of `benchmark` and `pbenchmark`.  We could store them in source, but using multiple dispatch might become difficult at some point. 

Yes. Let's use pathof(MCMCBenchmarks)  since that is giving you problems. Feel free to change it (I'm not sure how to use pathof yet).

I don't think cd(pwd) is necessary. So we can delete that. 

You are right. Each call to addprocs(n) is cumulative. So you do not want to execute addprocs(n) more than once or else you will have more than n . When I rerun the script, I omit addprocs(). However, I have used this function in the past to avoid the problem :

```
function setprocs(n)
    np = nprocs()-1
    m = max(n-np,0)
    addprocs(m)
end
```
which I tend to favor since it provides a safeguard against having too many procs. I sort of which base julia included this. Would you like me to add it? 

Let me know if you would like me to look at the issue you are having with LinearRegression.

Would you like me to merge your branch with master since I am familiar with the recent changes?

**Comment by goedman** [comment]
Hi Chris,

I’ve merged a minimal set (I think) of updates to master for OSX. TheGaussian_Parallel_Example.jl works fine now.
Can you try that on your system?

> Regarding your first question, I renamed Gaussian_example.jl to Gaussian_Parallel_Example.jl to make it distinct from the version in Gaussian_Example. In fact, I was thinking about making a parallel counterpart to each of the examples we have, and putting them in the same folder.

That’s a possibility. Is ether a reason not to always use benchmark?
> The reason I put the benchmark and pbenchmark functions in benchmark_configurations is to store different versions of benchmark. For example, if we want to vary Nd and some other variable, such as delta, we could have another file benchmark_configurations/Vary_Nd_delta.jl, which would house those versions of benchmark and pbenchmark. We could store them in source, but using multiple dispatch might become difficult at some point.
> 
Ok, undid (before merging) the change I was playing around with. Good point.
> Yes. Let's use pathof(MCMCBenchmarks) since that is giving you problems. Feel free to change it (I'm not sure how to use pathof yet).
> 
Done
> I don't think cd(pwd) is necessary. So we can delete that.
> 
Done
> You are right. Each call to addprocs(n) is cumulative. So you do not want to execute addprocs(n) more than once or else you will have more than n . When I rerun the script, I omit addprocs(). However, I have used this function in the past to avoid the problem :
> 
> function setprocs(n)
>     np = nprocs()-1
>     m = max(n-np,0)
>     addprocs(m)
> end
Included in Utilities.jl and exported from MCMCBenchmarks. If the Gaussian+Parallel_Example runs on your system I think we should be set.
> Let me know if you would like me to look at the issue you are having with LinearRegression.
Thanks a lot for giving me a push in the right direction! The last few days we’ve been getting ready to drive back to Colorado (from Washington, DC) so I expect to be mostly of the grid for about 8 days. I’ll have Internet a few evenings and while visiting some friends on our way back, but won’t be doing any useful work I guess.

I’ll continue the LinearRegression work when back in Denver.

Rob

**Comment by itsdfish** [comment]
Thanks Rob. Have a safe trip. Relax and enjoy your time off the grid!

**Comment by itsdfish** [comment]
P.S. The parallel set up works on my system.
