### ISSUE TITLE
MCMCChains v1

### ISSUE THREAD

**Issue by goedman** [StatisticalRethinkingJulia/MCMCBenchmarks.jl#62]
Hi Chris,

Cameron has released MCMCChains.jl v1.0. An important difference is that the variables in the Chains objects are no longer sorted by default. I'm in the process of updating CmdStan.jl to v5.5 where I revert the behavior back to sorted variables (by passing in `sorted=true` when creating the Chains object).

Travis is not fully functional right now, so it might take a few hours to test and merge this update.

Not sure how this all affects MCMCBenchmarks and if you have a preference for sorted or un-sorted?

Best,
Rob

**Comment by itsdfish** [comment]
Hello Rob. Thanks for the update. I cannot remember if mcmc benchmarks
expects the parameters to be sorted alphabetically but I think it would be
good to sort them just in case.

**Comment by goedman** [comment]
Done, v5.5 of CmdStan.jl
