### ISSUE TITLE
Separate Models/Benchmarks from package

### ISSUE THREAD

**Issue by itsdfish** [StatisticalRethinkingJulia/MCMCBenchmarks.jl#64]
Rob-

I was thinking about separating the models/Benchmarks from the core package. Some advantages include: easier access to models when installed as a non-development package, fewer dependencies in MCMCBenchmarks. Expanding on this later point, if I add a diff eq model, requiring DifferentialEquations would make MCMCBenchmarks bulky. Do you foresee any downside?

**Comment by goedman** [comment]
Hi Chris, not sure I fully understand what you are proposing, I would love to see the models separate from MCMCBenchmarks.jl. I started doing this in DynamicHMCModels where I added a subdirectory `benchmarks` that contain your models. This made it easier to run and detect a (trivial?) problem with one of the benchmarks.

But this is different from what you are suggesting I guess. You are thinking of having each benchmark as a separate package using common functions available in MCMCBenchmark.jl? That is also a nice step forwards. We would then have something like LBA_MCMCBenchmark.jl or MCMCBenchmark_DiffEq.jl? We could optionally rename MCMCBenchmarks.jl to MCMCBenchmarkBase.jl and over time phase out the current MCMCBenchmarks.jl?

**Comment by itsdfish** [comment]
Yeah. Similar to that but slightly different. I was thinking about organizing the code similar to DynamicHMC, Turing, and a few other packages, which separate the core library from examples. For example, the core NUTS algorithm and supporting functions are housed DynamicHMC, but examples are housed in DynamicHMCExamples.jl and your Statistical Rethinking repository. 

So basically, I would move the Examples and Models subdirectories in MCMCBenchmarks into a single repository, perhaps called MCMCBenchmarkModels MCMCBenchmarkSuite or something to that effect.

**Comment by goedman** [comment]
I see. Looks fine to me. Similar to Stan.jl as well.
