### ISSUE TITLE
Re-run benchmark and relink figures

### ISSUE THREAD

**Issue by itsdfish** [StatisticalRethinkingJulia/MCMCBenchmarks.jl#7]
I realized I did not configure num_samples and num_warmup correctly for CmdStan. This was fixed in the last commit. In CmdStan, total samples = num_samples + num_warmup, whereas in Turing  total samples = num_samples. I removed the additional 1000 samples, but the times are based on 3000 instead 2000. Given how fast CmdStan is, it may not affect the timing. 

I recommend using` pyplot()` for the plots because it has less crowding.

I can run this if you would like.

**Comment by goedman** [comment]
I’ll try to get the samplers running. On your system, CmdStan is clearly running. Any of the other samplers? Or is just the DynamicHMC not working?

**Comment by itsdfish** [comment]
Currently, the LBA does not work with DynamicHMC. All of the other samplers work with Gaussian. However, DynamicNUTS and Turing/AdvancedHMC NUTS do not work together due to an issue with MCMCChains.

No worries about running the Gaussian benchmark. I started it about an hour ago.

**Comment by itsdfish** [comment]
I updated master with new benchmarks and fixed the links.
