### ISSUE TITLE
Epsilon for DynamicHMC

### ISSUE THREAD

**Issue by itsdfish** [StatisticalRethinkingJulia/MCMCBenchmarks.jl#9]
Currently, we do not collect epsilon for DynamicHMC. Do you know if there is a way to do so?

**Comment by goedman** [comment]
It's in NUTS_tuned, e.g. `NUTS_tuned.ϵ`.

**Comment by itsdfish** [comment]
Thanks. I'll look into that later and see if there is a way to add it to the chains object.
